import { Inter } from "next/font/google";
import "@fontsource/montserrat"; // Defaults to weight 400 with normal style
import "@fontsource/montserrat/700.css"; // Weight 700
import "./globals.css";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
